<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sam</groupId>
        <artifactId>blog</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>blog-app</artifactId>
    <name>blog-app</name>
    <description>Demo project for Spring Boot</description>
    <packaging>jar</packaging>

    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>blog-core</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>blog-user</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>blog-auth</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>blog-mailer</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <!-- POST -->
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>post-api</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>post-impl</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <!-- COMMENT -->
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>comment-api</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>comment-impl</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <!-- LIKE -->
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>like-api</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>like-impl</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>blog-share</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>blog-notification</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.sam</groupId>
            <artifactId>blog-message</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
            </plugin>
        </plugins>
    </build>
</project>
